version: "3"
services:
  razor-go:
    #platform: linux/x86_64 #Uncomment for silicon based MAC
    container_name: razor-go
    image: razornetwork/razor-go
    entrypoint: /bin/bash
    build: .
    tty: true
    volumes:
      - $HOME/.razor:/root/.razor
    networks:
      - razor_network
networks:
  razor_network:
    name: razor_network
    driver: bridge
